/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export type MediaId = bigint;
export interface MediaItemView {
  'id' : MediaId,
  'blob' : ExternalBlob,
  'name' : string,
  'projectId' : ProjectId,
  'caption' : string,
  'mediaType' : MediaType,
  'uploadedAt' : bigint,
}
export type MediaType = { 'audio' : null } |
  { 'video' : null } |
  { 'photo' : null };
export interface PortfolioView {
  'media' : Array<MediaItemView>,
  'projects' : Array<ProjectView>,
  'owner' : string,
  'profile' : [] | [UserProfile],
}
export type ProjectId = bigint;
export interface ProjectView {
  'id' : ProjectId,
  'title' : string,
  'owner' : string,
  'createdAt' : bigint,
  'description' : string,
  'updatedAt' : bigint,
}
export interface UserProfile { 'name' : string, 'avatar' : [] | [ExternalBlob] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addMedia' : ActorMethod<
    [ProjectId, string, MediaType, ExternalBlob, string],
    MediaItemView
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProject' : ActorMethod<[string, string], ProjectView>,
  'deleteMedia' : ActorMethod<[MediaId], boolean>,
  'deleteProject' : ActorMethod<[ProjectId], boolean>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getPortfolio' : ActorMethod<[Principal], PortfolioView>,
  'getProject' : ActorMethod<[ProjectId], [] | [ProjectView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyProjects' : ActorMethod<[], Array<ProjectView>>,
  'listProjectMedia' : ActorMethod<[ProjectId], Array<MediaItemView>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateProject' : ActorMethod<[ProjectId, string, string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];